language: cpp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y g++-multilib libbz2-dev:i386
install:
- git clone --recursive https://github.com/boostorg/boost.git $TRAVIS_BUILD_DIR/../boost
  && cd $TRAVIS_BUILD_DIR/../boost && ./bootstrap.sh && ./b2 --without-python address-model=32 stage
- git clone https://github.com/open-source-parsers/jsoncpp.git $TRAVIS_BUILD_DIR/../jsoncpp
  && cd $TRAVIS_BUILD_DIR/../jsoncpp && python amalgamate.py
- git clone https://github.com/zaphoyd/websocketpp.git $TRAVIS_BUILD_DIR/../websocketpp
- git clone https://github.com/ValveSoftware/source-sdk-2013.git $TRAVIS_BUILD_DIR/../source-sdk-2013
  && ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src/utils/ExternalExtensions && cat $TRAVIS_BUILD_DIR/build_tools/project.vgc >> $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src/vpc_scripts/projects.vgc && cp $TRAVIS_BUILD_DIR/build_tools/createexternalextensions $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src && chmod +x $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src/createexternalextensions && cd $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src && devtools/bin/vpc +ExternalExtensions /mksln ExternalExtensions /define:TRAVIS
- wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz -O $TRAVIS_BUILD_DIR/../steam-runtime-sdk_latest.tar.xz && tar xvf $TRAVIS_BUILD_DIR/../steam-runtime-sdk_latest.tar.xz -C $TRAVIS_BUILD_DIR/..
  && cd $TRAVIS_BUILD_DIR/../steam-runtime-sdk_* && ./setup.sh --auto-update && export STEAM_RUNTIME_HOST_ARCH=$(dpkg --print-architecture) && export STEAM_RUNTIME_TARGET_ARCH=i386 && export STEAM_RUNTIME_ROOT=$PWD/runtime/$STEAM_RUNTIME_TARGET_ARCH && export PATH="$PWD/bin:$PATH" && ln -s /usr/include/boost $STEAM_RUNTIME_ROOT/usr/include/boost && cp -s /usr/lib/libboost* $STEAM_RUNTIME_ROOT/usr/lib/
script:
- ulimit -Sm 262144
- cd $TRAVIS_BUILD_DIR/../source-sdk-2013/mp/src && make -f ExternalExtensions.mak
